spring.application.name=subscriptionapi
server.port=8080
server.servlet.context-path=/api

# JPA common settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.com.subscriptionapi=DEBUG
